version: "3.8"

services:
  backend:
    build: .
    container_name: textil-pos-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      TZ: America/Lima
      JAVA_OPTS: "-Duser.timezone=America/Lima"
      STORAGE_BASE_PATH: /app/storage
      SUNAT_CERT_BASE_PATH: /app/storage/sunat/certificados
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks:
      - textil-network

networks:
  textil-network:
    external: true