package com.sistemapos.sistematextil.model;

public enum CrmWhatsappAiDeliveryType {
    AUTOMATIC_RESPONSE,
    PRODUCT_IMAGE,
    SIZE_GUIDE_IMAGE,
    NEW_PRODUCT_ANNOUNCEMENT,
    CATALOG_PRODUCT_CARD,
    PRODUCT_PROMOTION_SUGGESTION,
    CART_PROMOTION_SUGGESTION,
    HANDOFF_NOTICE,
    PAYMENT_REGISTERED,
    PAYMENT_RETRY,
    PAYMENT_REJECTED,
    SALE_COMPLETED
}
